<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */
/**
 * Fires at start of header.php, immediately before `genesis_title` action hook to render the Doctype content.
 *
 * @since 1.3.0
 */
do_action('genesis_doctype');

/**
 * Fires immediately after `genesis_doctype` action hook, in header.php to render the document title.
 *
 * @since 1.0.0
 */
do_action('genesis_title');

/**
 * Fires immediately after `genesis_title` action hook, in header.php to render the meta elements.
 *
 * @since 1.0.0
 */
do_action('genesis_meta');
?>

<meta http-equiv="content-type" content="<?php bloginfo('html_type'); ?>; charset=<?php bloginfo('charset'); ?>" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

<script type="text/javascript">
    var templateUrl = '<?= get_site_url(); ?>';
    var logoutURL = '<?php echo wp_logout_url(home_url()); ?>';
</script>

<?php
    // Tracking pixels users can turn off through the cookie law checkbox -- defaults to yes
	if(!isset($_COOKIE['cookielawinfo-checkbox-non-necessary']) || $_COOKIE['cookielawinfo-checkbox-non-necessary'] == "yes" ) {
?>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-51157-36"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('set', 'linker', {
			'accept_incoming': true,
			'domains': [
				'make.co',
				'makermedia.auth0.com',
				'stagemakehub.wpengine.com',
				'devmakehub.wpengine.com'
			]
		});
		gtag('js', new Date());
		gtag('config', 'UA-51157-36');
	</script>
<?php } // end cookie law if ?>

<?php
wp_head(); // We need this for plugins.
?>
</head>
<?php
genesis_markup(
        array(
            'open' => '<body %s>',
            'context' => 'body',
        )
);

/**
 * Fires immediately after the body element opening markup.
 *
 * @since 1.0.0
 */
do_action('genesis_before');

genesis_markup(
        array(
            'open' => '<div id="page" %s>',
            'context' => 'site-container',
        )
);

/**
 * Fires immediately after the site container opening markup, before `genesis_header` action hook.
 *
 * @since 1.0.0
 */
do_action('genesis_before_header');

/**
 * Fires to display the main header content.
 *
 * @since 1.0.2
 */
// do_action( 'genesis_header' ); We're overwriting this with our own header stuff
?>

<?php
    // Tracking pixels users can turn off through the cookie law checkbox -- defaults to yes
	if(!isset($_COOKIE['cookielawinfo-checkbox-non-necessary']) || $_COOKIE['cookielawinfo-checkbox-non-necessary'] == "yes" ) {
?>
	<!-- Google Tag Manager (noscript) -->
	<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5PRW4M2" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<!-- End Google Tag Manager (noscript) -->
<?php } // end cookie law if ?>

	<?php
		// Nav Level 1 and Hamburger
		require_once(WP_CONTENT_DIR.'/universal-assets/v1/page-elements/universal-topnav.html');
	?>
	<div id="universal-subnav" class="nav-level-2">
		<?php
			wp_nav_menu( array(
			  'menu'              => 'secondary_universal_menu',
			  'theme_location'    => 'secondary_universal_menu',
			  'container'         => '',
			  'container_class'   => '',
			  'link_before'       => '<span>',
			  'link_after'        => '</span>',
			  'menu_class'        => 'nav navbar-nav',
			  'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
			  'walker'            => new wp_bootstrap_navwalker())
			);
		?>
	</div>


<?php
/**
 * Fires immediately after the `genesis_header` action hook, before the site inner opening markup.
 *
 * @since 1.0.0
 */
do_action('genesis_after_header');

genesis_markup(
        array(
            'open' => '<div class="main-content site-content container-fluid">',
            'context' => 'site-inner',
        )
);
genesis_structural_wrap('site-inner');
?>
